import React, { forwardRef } from 'react';

const CashFlowPdf = forwardRef(({ summary, runningBalance, byCategory }, ref) => {
  return (
    <div ref={ref} style={{ padding: '16px', fontFamily: 'Inter, Arial, sans-serif', color: '#0f172a', width: '100%' }}>
      <h2 style={{ marginBottom: '8px' }}>Cash Flow Statement</h2>
      <p style={{ marginTop: 0, marginBottom: '16px', color: '#475569' }}>Generated by BudgetBuddy</p>

      <div style={{ display: 'flex', gap: '12px', marginBottom: '16px', flexWrap: 'wrap' }}>
        <SummaryCard label="Inflow" value={summary?.inflow} />
        <SummaryCard label="Outflow" value={summary?.outflow} />
        <SummaryCard label="Net" value={summary?.net} />
      </div>

      <h3 style={{ marginBottom: '8px' }}>By Category (Debit)</h3>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thTd}>Category</th>
            <th style={thTd}>Total</th>
          </tr>
        </thead>
        <tbody>
          {(byCategory || []).map((row, idx) => (
            <tr key={idx}>
              <td style={thTd}>{row.category}</td>
              <td style={thTd}>Rs {row.total?.toLocaleString?.() || 0}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h3 style={{ margin: '16px 0 8px' }}>Running Balance</h3>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thTd}>Date</th><th style={thTd}>Type</th><th style={thTd}>Account</th><th style={thTd}>Category</th><th style={thTd}>Description</th><th style={thTd}>Amount</th><th style={thTd}>Balance</th>
          </tr>
        </thead>
        <tbody>
          {(runningBalance || []).map((row, idx) => (
            <tr key={idx}>
              <td style={thTd}>{new Date(row.date).toLocaleDateString()}</td>
              <td style={thTd}>{row.type}</td>
              <td style={thTd}>{row.account}</td>
              <td style={thTd}>{row.category}</td>
              <td style={thTd}>{row.description}</td>
              <td style={thTd}>Rs {row.amount?.toLocaleString?.() || 0}</td>
              <td style={thTd}>Rs {row.balance?.toLocaleString?.() || 0}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
});

const SummaryCard = ({ label, value }) => (
  <div style={{ border: '1px solid #e2e8f0', borderRadius: 8, padding: 12, minWidth: 140 }}>
    <div style={{ color: '#475569', fontSize: 12 }}>{label}</div>
    <div style={{ fontWeight: 700, fontSize: 16 }}>Rs {value?.toLocaleString?.() || 0}</div>
  </div>
);

const tableStyle = { width: '100%', borderCollapse: 'collapse', marginBottom: '12px' };
const thTd = { border: '1px solid #e2e8f0', padding: '6px 8px', textAlign: 'left', fontSize: 12 };

export default CashFlowPdf;
