import React, { forwardRef } from 'react';

const MonthlySummaryPdf = forwardRef(({ monthLabel, budget, spent, categories = [] }, ref) => {
  const remaining = Math.max(0, (budget || 0) - (spent || 0));
  return (
    <div ref={ref} style={{ padding: '16px', fontFamily: 'Inter, Arial, sans-serif', color: '#0f172a', width: '100%' }}>
      <h2 style={{ marginBottom: '8px' }}>Monthly Summary - {monthLabel || 'Current Month'}</h2>
      <p style={{ marginTop: 0, marginBottom: '16px', color: '#475569' }}>Generated by BudgetBuddy</p>

      <div style={{ display: 'flex', gap: '12px', marginBottom: '16px', flexWrap: 'wrap' }}>
        <SummaryCard label="Budget" value={budget} />
        <SummaryCard label="Spent" value={spent} />
        <SummaryCard label="Remaining" value={remaining} />
      </div>

      <h3 style={{ marginBottom: '8px' }}>Category Breakdown</h3>
      <table style={tableStyle}>
        <thead>
          <tr>
            <th style={thTd}>Category</th>
            <th style={thTd}>Spent</th>
          </tr>
        </thead>
        <tbody>
          {categories.map((row, idx) => (
            <tr key={idx}>
              <td style={thTd}>{row.categoryName || row.name || 'Uncategorized'}</td>
              <td style={thTd}>Rs {row.totalSpent?.toLocaleString?.() || 0}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
});

const SummaryCard = ({ label, value }) => (
  <div style={{ border: '1px solid #e2e8f0', borderRadius: 8, padding: 12, minWidth: 140 }}>
    <div style={{ color: '#475569', fontSize: 12 }}>{label}</div>
    <div style={{ fontWeight: 700, fontSize: 16 }}>Rs {value?.toLocaleString?.() || 0}</div>
  </div>
);

const tableStyle = { width: '100%', borderCollapse: 'collapse', marginBottom: '12px' };
const thTd = { border: '1px solid #e2e8f0', padding: '6px 8px', textAlign: 'left', fontSize: 12 };

export default MonthlySummaryPdf;
